spring:
  datasource:
    url: jdbc:h2:mem:votingdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

blockchain:
  difficulty: 4
  mining-reward: 12.5

logging:
  level:
    com.votex: DEBUG
    org.springframework: INFO